os: linux

dist: bionic

language: c

install:
  - sudo apt-get install -yy llvm-6.0-dev
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval $(opam config env)

script: make deps && make && make test

env:
  jobs:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
